version: '2.4'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "mn"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password123"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - mn-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mn-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5000"
      ConnectionStrings__DefaultConnection: "Host=db;Database=mn;Username=postgres;Password=Password123"

      # ← ЯДРО: переменные JWT даны ЗАГЛАВНЫМИ
      JWT__KEY: "YourStrongSecretKeyHere"
      JWT__ISSUER: "MoralNavigatorAPI"
      JWT__AUDIENCE: "MoralNavigatorUsers"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/swagger/v1/swagger.json || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5000:5000"
    networks:
      - mn-net
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mn-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: "http://backend:5000"
    ports:
      - "3000:80"
    networks:
      - mn-net
    restart: on-failure

volumes:
  dbdata:

networks:
  mn-net:
    driver: bridge
